export enum AuditTargetType {
  USER = 'user',
  CLIENT = 'client',
  ORGANISATION = 'organisation',
  PROGRAM = 'program',
  COHORT = 'cohort',
  ENROLLMENT = 'enrollment',
  SESSION = 'session',
  INVOICE = 'invoice',
  PAYMENT = 'payment',
  COMMUNICATION = 'communication',
  TEMPLATE = 'template',
  SETTINGS = 'settings',
  ROLE = 'role',
  PERMISSION = 'permission',
  EMPLOYEE = 'employee',
  PARTNER = 'partner',
  ASSIGNMENT = 'assignment',
  NOTIFICATION = 'notification',
}
